apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stickynotes
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stickynotes
    repoURL: https://github.com/1Jayso/stickynotes-digitalOcean
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}